알림기능: 인터페이스, 구현체, 기능 연결
boostcampwm-2024/iOS01-Ret-s-Talk pull request #145
Opened 2024-11-28 16:01 UTC by 1win2

##  📌 관련 이슈

- closed: #127 

## ✨ 세부 내용
### 구현내용
- 인터페이스 NotificationManageable 
- 구현체 NotificationManager
- UserSettingView 에 기능 연결

### 동작화면
<img src="https://github.com/user-attachments/assets/eda1d911-596d-478e-80ac-201405c60077" width="250"/>

## ✍️ 고민한 내용
뷰와 모델을 연결하는 과정에서 동시성 관리를 하지 못해 CompletionHandler 전달과정에 이슈가 있었습니다. 알림권한 요청에 대한 핸들러에서 @Sendable 을 처리해 안전하게 전달하도록 해결했습니다.

## ⌛ 소요 시간
1D

2024-11-30 04:25 UTC, MoonGoon72 approved these changes
수고하셨습니다!

2024-11-30 04:27 UTC, gen-com requested changes

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
> +        guard let userSettingManager = userSettingManager as? UserSettingManager else { fatalError() }
실패하지 않아야만 하는 캐스팅이지만, 이렇게 해서 내려주게 되는 것은 추상화의 이점을 십분 활용하지 못하는 것 같습니다.

UserSettingView가 제너릭을 사용하고, 전역상수는 밖으로 빼는 것은 어떤가요 ?

```swift
// MARK: - Constants

fileprivate enum UserSettingViewTexts {
    static let firstSectionTitle = "사용자 정보"
    static let secondSectionTitle = "클라우드"
    static let thirdSectionTitle = "알림"
    static let fourthSectionTitle = "앱 정보"
}
```

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
> +        self.notificationManager = NotificationManager()
```swift
required init?(coder: NSCoder) { ... }
```
이 부분은 다른 화면에서도 일괄적으로 어떻게 처리할 지 생각해봐야 할 것 같습니다.

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +
case 문 사이에 공백을 둘 필요는 없어 보입니다.

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +                self.requestPermission(completion: completion)
self 캡처를 했을 때 메모리 누수가 없을까요 ?

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +    func checkAndRequestPermission(completion: @Sendable @escaping (Bool) -> Void) {
Sendable 클로저는 어떤 의미일까요 ?

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +            }
```suggestion
            guard error != nil
            else {
                completion(granted)
                return
            }
```

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        content.sound = UNNotificationSound.default
사소하지만 노티피케이션 컨텐트를 만드는 계산 프로퍼티나, 함수르 빼면 이 메소드를 읽는 데 더 좋을 것 같아요.

이 메소드(scheduleNotification)가 해야할 것은 노티피케이션을 스케줄 하는 것이 메인이니까요

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        center.add(request) { _ in }
클로저가 있는 걸 보니 요청이 실패할 수도 있는 것 같은데 무시해도 될까요 ?

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        UNUserNotificationCenter.current().removeAllPendingNotificationRequests()
우리가 요청만 것만 삭제해주나요 ? 이렇게 전부 날려도 되나요 ?

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        ]
계산 프로퍼티로, 아예 여기서 랜덤값을 날리는 것은 어떤가요 ?

2024-11-30 04:27 UTC, gen-com commented on RetsTalk/RetsTalk/User/UserSettingView.swift
> +    }
뷰에 비즈니스 로직이 들어가는 것은 좋지 않습니다. 뷰는 자신이 보여지는 상태와 액션에만 집중해야 합니다.

사용자 설정 매니저가 노티피케이션 매니저를 소유한 상태가 되고, 뷰에서는 그냥 사용자 설정 매니저에게 명령만 할 수 있는 구조는 어떤가요 ?

2024-11-30 06:58 UTC, alstjr7437 approved these changes
고생하셨습니다!

2024-12-01 02:48 UTC, 1win2 commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +    func checkAndRequestPermission(completion: @Sendable @escaping (Bool) -> Void) {
클로저와 캡처 대상을 안전하게 전송한다는 의미같아요!

2024-12-01 02:54 UTC, 1win2 commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        center.add(request) { _ in }
우선 정상 작동을 가정하고 넘기도록했습니다. 오류처리를 통해 사용자에게 알려주는건 추후에..해볼게요

2024-12-01 02:56 UTC, 1win2 commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        UNUserNotificationCenter.current().removeAllPendingNotificationRequests()
해당 앱에서 작성한 알림만 전부 삭제합니다.

2024-12-01 03:00 UTC, 1win2 commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +        ]
정적상수로 만들어보겠습니다!

2024-12-01 03:04 UTC, 1win2 commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +            }
분기 지점이 하나라 생각없이 쭉 작성한 것 같아요.
`error == nil` 로 변경하는게 가독성이 좋을 것 같군요

2024-12-01 06:03 UTC, gen-com approved these changes

2024-12-01 06:03 UTC, gen-com commented on RetsTalk/RetsTalk/User/Model/NotificationManager.swift
> +            return Texts.notificationBody.randomElement() ?? Texts.notificationDefaultBody
return문 생략 가능합니다.

2024-12-01 06:03 UTC, gen-com commented on RetsTalk/RetsTalk/User/UserSettingView.swift
> +struct UserSettingView<T: UserSettingManageable>: View {
간단히 T라고 했지만, 더 자세한 이름이어도 될 거 같아요.

2024-12-01 06:24 UTC, merged